In [1]:
import numpy as np
import random
from matplotlib import pyplot as plt
import scipy as sp
import networkx as nx
import collections
import time
import math

In [21]:
start = time.time()

testlist = [False]*10000

end = time.time()

print(end-start)

0.0


In [6]:
[[0 for col in range(50)] for row in range(50)]

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  

In [46]:
testd = {1,2,3,4,5}
testd.add(354)
testd
di = {}

In [67]:
for i in testd:
    di[i] = random.choice({100,200,300})
di

TypeError: 'set' object is not subscriptable

In [31]:
G = nx.MultiDiGraph()
G.add_edge(0, 1)
G.add_edge(0, 3)
G.add_edge(0, 4)
G.add_edge(1, 0)
G.add_edge(3, 0)
G.add_edge(4, 0)
G.add_edge(1, 4)
G.add_edge(1, 5)
G.add_edge(1, 2)
G.add_edge(4, 1)
G.add_edge(5, 1)
G.add_edge(2, 1)
G.add_edge(2, 4)
G.add_edge(2, 5)
G.add_edge(2, 6)
G.add_edge(4, 2)
G.add_edge(5, 2)
G.add_edge(6, 2)
G.add_edge(3, 4)
G.add_edge(4, 3)
G.add_edge(4, 5)
G.add_edge(5, 4)
G.add_edge(5, 6)
G.add_edge(6, 5)

G2 = nx.MultiDiGraph()
G2.add_edge(0,1)
G2.add_edge(1,0)
G2.add_edge(0,2)
G2.add_edge(2,0)
G2.add_edge(1,2)
G2.add_edge(2,1)

G3 = nx.MultiDiGraph()
G3.add_edge(0,1)
G3.add_edge(1,0)
G3.add_edge(0,2)
G3.add_edge(2,0)
G3.add_edge(0,3)
G3.add_edge(3,0)
G3.add_edge(1,2)
G3.add_edge(2,1)
G3.add_edge(1,3)
G3.add_edge(3,1)
G3.add_edge(2,3)
G3.add_edge(3,2)

G4 = nx.MultiDiGraph()
G4.add_edge(0,1)
G4.add_edge(1,0)
G4.add_edge(0,2)
G4.add_edge(2,0)
G4.add_edge(0,3)
G4.add_edge(3,0)
G4.add_edge(1,2)
G4.add_edge(2,1)
G4.add_edge(1,3)
G4.add_edge(3,1)
G4.add_edge(2,3)
G4.add_edge(3,2)
G4.add_edge(2,4)
G4.add_edge(4,2)
G4.add_edge(3,4)
G4.add_edge(4,3)

A = nx.to_scipy_sparse_matrix(G4, nodelist=[0, 1, 2, 3, 4]) # 5 nodes
B = nx.to_scipy_sparse_matrix(G, nodelist=[0, 1, 2, 3, 4, 5, 6]) # 7 nodes
C = nx.to_scipy_sparse_matrix(G2, nodelist=[0, 1, 2]) # 3 nodes
D = nx.to_scipy_sparse_matrix(G3, nodelist=[0, 1, 2, 3]) # 4 nodes

In [32]:
print(A.todense())

[[0 1 1 1 0]
 [1 0 1 1 0]
 [1 1 0 1 1]
 [1 1 1 0 1]
 [0 0 1 1 0]]


In [64]:
test = {}
mat = A.todense()
for i in range(5):
    if mat[1,i] == 1:
        print(i)

0
2
3


In [42]:
mat[1]

matrix([[1, 0, 1, 1, 0]], dtype=int32)

In [72]:
print(2 in {1,2,3})

True


In [95]:
test = np.empty(0, dtype = 'int32')

In [97]:
np.append(test,3)

array([3])

In [125]:
zero =  np.zeros((5,5), dtype = "int32")
test = np.array([0,2,3,4])
for i in range(len(test)-1):
    zero[test[i], test[i+1]] = 1
    zero[test[i+1], test[i]] = 1

In [173]:
mat[0]

matrix([[0, 1, 1, 1, 0]], dtype=int32)

In [165]:
np.unique(zero, return_counts = True)

(array([0, 1]), array([19,  6], dtype=int64))

In [133]:
test = [False,True,False,False,True]
[i for i in range(len(test)) if test[i] == True]

[1, 4]

In [159]:
test = np.array([0,2,3,4])
cop = np.copy(test)
np.append(cop,1)
cop

array([0, 2, 3, 4])

In [154]:
test[:np.where(test == 2)[0][0]+1]

array([0, 2])

In [ ]:
x = 2
while x<5:
    if x==1:
        print("fuck!")
        continue

In [162]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])