In [16]:
import numpy as np
import random
from matplotlib import pyplot as plt
from scipy.sparse import csr_matrix

In [74]:
row = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
col = np.array([0, 1, 2, 0, 1, 2, 0, 1, 2])
  
# taking data
data = np.array([0,0,0,0,0,0,0,0,0])
  
# creating sparse matrix
sparseMatrix = csr_matrix((data, (row, col)), 
                          shape = (3, 3)).toarray()
  
# print the sparse matrix
print(sparseMatrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [58]:
sparseMatrix.__len__()

4

### Uniform Spanning Tree

A spanning tree of a finite connected graph G is a connected subgraph of G containing every vertex and no cycles.  
(Ref: https://mathweb.ucsd.edu/~jschwein/LERW.pdf)

### Wilson's Algorithm

0. Create empty cells
1. Set the starting position
2. While it's not a spanning tree
    - Perform LERW in a network  
        1) Pick any random position  
        2) Perform a random walk  
        3) Check if the position is already visited  
            -- If yes, erase the loop and restart the walk
            -- If no, add to the trace
        4) Check if the current position is already in the trace

In [972]:
def LERW(start_position, goal):
    visited_cell = []
    current_position = start_position
    visited_cell.append(current_position)
    while current_position != goal:
        neighbors = [(current_position[0],current_position[1]-1),(current_position[0],current_position[1]+1),
                     (current_position[0]-1,current_position[1]),(current_position[0]+1,current_position[1])] # (left,right,up,down)
        feasible_neighbors = [i for i in neighbors if (i[0] >= 0 and i[0] <= dim-1) and (i[1] >= 0 and i[1] <= dim-1)]
        next_position = random.choice(feasible_neighbors)
        # Check if there is a loop
        if next_position not in visited_cell:
            visited_cell.append(next_position)
        else:
            # reset path
            if visited_cell.index(next_position) == 0:
                visited_cell = [visited_cell[0]]
            else:
                visited_cell = visited_cell[:visited_cell.index(next_position)+1]

        current_position = next_position
    return start_position, goal, current_position, visited_cell

def cont_LERW(remaining_cell):
    new_path = []
    new_start_position = random.choice(remaining_cell)
    current_position = new_start_position
    new_path.append(current_position)
    
    while current_position not in set_path:
        neighbors = [(current_position[0],current_position[1]-1),(current_position[0],current_position[1]+1),
                     (current_position[0]-1,current_position[1]),(current_position[0]+1,current_position[1])] # (left,right,up,down)
        feasible_neighbors = [i for i in neighbors if (i[0] >= 0 and i[0] <= dim-1) and (i[1] >= 0 and i[1] <= dim-1)]
        next_position = random.choice(feasible_neighbors)
        
        if (next_position not in new_path) and (next_position not in set_path):
            new_path.append(next_position)
            
        if next_position in set_path:
            break
            
        if next_position in new_path:
            if new_path.index(next_position) == 0:
                new_path = [new_path[0]]
            else:
                new_path = new_path[:new_path.index(next_position)+1]
                
        # check if current_position is already in the path to goal.
        current_position = next_position
    return new_start_position, current_position, new_path

In [977]:
# 0. Create empty cells

def Wilson_generate(spMatrix):
    dim = sparseMatrix.__len__()
    universe = [(i,j) for i in range(spMatrix.__len__()) for j in range(spMatrix.__len__())]
    start_position = random.choice(not_visited_cell)
    universe.remove(start_position)
    goal = random.choice(not_visited_cell)
    set_path = LERW(start_position, goal)[3]
    
    # After obtaining the first path to the goal, generate the next RW.
    remaining_cell = [i for i in universe if i not in set_path]
    while len(remaining_cell) != 0:
        set_path.append(cont_LERW(remaining_cell)[2])
        remaining_cell = [i for i in universe if i not in set_path]
    return set_path, remaining_cell

In [978]:
Wilson_generate(sparseMatrix)

KeyboardInterrupt: 

In [970]:
cont_LERW([(0, 0), (0, 1), (0, 2), (1, 1), (1, 2), (2, 2)])

([(0, 0), (0, 1), (0, 2), (1, 1), (1, 2), (2, 2)],
 (1, 1),
 (2, 2),
 [(1, 1), (2, 1), (2, 2), (1, 2)])